/*
 * OWASP Dependency-Track
 * REST API of OWASP Dependency-Track
 *
 * The version of the OpenAPI document: 4.12.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.api;

import com.github.fluorumlabs.dtrack.ApiCallback;
import com.github.fluorumlabs.dtrack.ApiClient;
import com.github.fluorumlabs.dtrack.ApiException;
import com.github.fluorumlabs.dtrack.ApiResponse;
import com.github.fluorumlabs.dtrack.Configuration;
import com.github.fluorumlabs.dtrack.Pair;
import com.github.fluorumlabs.dtrack.ProgressRequestBody;
import com.github.fluorumlabs.dtrack.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.github.fluorumlabs.dtrack.model.Analysis;
import com.github.fluorumlabs.dtrack.model.AnalysisRequest;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AnalysisApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AnalysisApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AnalysisApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for retrieveAnalysis
     * @param component The UUID of the component (required)
     * @param vulnerability The UUID of the vulnerability (required)
     * @param project The UUID of the project (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An analysis trail </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project, component, or vulnerability could not be found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call retrieveAnalysisCall(UUID component, UUID vulnerability, UUID project, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/analysis";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (project != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("project", project));
        }

        if (component != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("component", component));
        }

        if (vulnerability != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("vulnerability", vulnerability));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call retrieveAnalysisValidateBeforeCall(UUID component, UUID vulnerability, UUID project, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'component' is set
        if (component == null) {
            throw new ApiException("Missing the required parameter 'component' when calling retrieveAnalysis(Async)");
        }

        // verify the required parameter 'vulnerability' is set
        if (vulnerability == null) {
            throw new ApiException("Missing the required parameter 'vulnerability' when calling retrieveAnalysis(Async)");
        }

        return retrieveAnalysisCall(component, vulnerability, project, _callback);

    }

    /**
     * Retrieves an analysis trail
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_VULNERABILITY&lt;/strong&gt;&lt;/p&gt;
     * @param component The UUID of the component (required)
     * @param vulnerability The UUID of the vulnerability (required)
     * @param project The UUID of the project (optional)
     * @return Analysis
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An analysis trail </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project, component, or vulnerability could not be found </td><td>  -  </td></tr>
     </table>
     */
    public Analysis retrieveAnalysis(UUID component, UUID vulnerability, UUID project) throws ApiException {
        ApiResponse<Analysis> localVarResp = retrieveAnalysisWithHttpInfo(component, vulnerability, project);
        return localVarResp.getData();
    }

    /**
     * Retrieves an analysis trail
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_VULNERABILITY&lt;/strong&gt;&lt;/p&gt;
     * @param component The UUID of the component (required)
     * @param vulnerability The UUID of the vulnerability (required)
     * @param project The UUID of the project (optional)
     * @return ApiResponse&lt;Analysis&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An analysis trail </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project, component, or vulnerability could not be found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Analysis> retrieveAnalysisWithHttpInfo(UUID component, UUID vulnerability, UUID project) throws ApiException {
        okhttp3.Call localVarCall = retrieveAnalysisValidateBeforeCall(component, vulnerability, project, null);
        Type localVarReturnType = new TypeToken<Analysis>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieves an analysis trail (asynchronously)
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_VULNERABILITY&lt;/strong&gt;&lt;/p&gt;
     * @param component The UUID of the component (required)
     * @param vulnerability The UUID of the vulnerability (required)
     * @param project The UUID of the project (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> An analysis trail </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project, component, or vulnerability could not be found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call retrieveAnalysisAsync(UUID component, UUID vulnerability, UUID project, final ApiCallback<Analysis> _callback) throws ApiException {

        okhttp3.Call localVarCall = retrieveAnalysisValidateBeforeCall(component, vulnerability, project, _callback);
        Type localVarReturnType = new TypeToken<Analysis>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for updateAnalysis
     * @param analysisRequest  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The created analysis </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project, component, or vulnerability could not be found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateAnalysisCall(AnalysisRequest analysisRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = analysisRequest;

        // create path and map variables
        String localVarPath = "/v1/analysis";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call updateAnalysisValidateBeforeCall(AnalysisRequest analysisRequest, final ApiCallback _callback) throws ApiException {
        return updateAnalysisCall(analysisRequest, _callback);

    }

    /**
     * Records an analysis decision
     * &lt;p&gt;Requires permission &lt;strong&gt;VULNERABILITY_ANALYSIS&lt;/strong&gt;&lt;/p&gt;
     * @param analysisRequest  (optional)
     * @return Analysis
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The created analysis </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project, component, or vulnerability could not be found </td><td>  -  </td></tr>
     </table>
     */
    public Analysis updateAnalysis(AnalysisRequest analysisRequest) throws ApiException {
        ApiResponse<Analysis> localVarResp = updateAnalysisWithHttpInfo(analysisRequest);
        return localVarResp.getData();
    }

    /**
     * Records an analysis decision
     * &lt;p&gt;Requires permission &lt;strong&gt;VULNERABILITY_ANALYSIS&lt;/strong&gt;&lt;/p&gt;
     * @param analysisRequest  (optional)
     * @return ApiResponse&lt;Analysis&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The created analysis </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project, component, or vulnerability could not be found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Analysis> updateAnalysisWithHttpInfo(AnalysisRequest analysisRequest) throws ApiException {
        okhttp3.Call localVarCall = updateAnalysisValidateBeforeCall(analysisRequest, null);
        Type localVarReturnType = new TypeToken<Analysis>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Records an analysis decision (asynchronously)
     * &lt;p&gt;Requires permission &lt;strong&gt;VULNERABILITY_ANALYSIS&lt;/strong&gt;&lt;/p&gt;
     * @param analysisRequest  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> The created analysis </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project, component, or vulnerability could not be found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call updateAnalysisAsync(AnalysisRequest analysisRequest, final ApiCallback<Analysis> _callback) throws ApiException {

        okhttp3.Call localVarCall = updateAnalysisValidateBeforeCall(analysisRequest, _callback);
        Type localVarReturnType = new TypeToken<Analysis>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
