/*
 * OWASP Dependency-Track
 * REST API of OWASP Dependency-Track
 *
 * The version of the OpenAPI document: 4.12.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.api;

import com.github.fluorumlabs.dtrack.ApiCallback;
import com.github.fluorumlabs.dtrack.ApiClient;
import com.github.fluorumlabs.dtrack.ApiException;
import com.github.fluorumlabs.dtrack.ApiResponse;
import com.github.fluorumlabs.dtrack.Configuration;
import com.github.fluorumlabs.dtrack.Pair;
import com.github.fluorumlabs.dtrack.ProgressRequestBody;
import com.github.fluorumlabs.dtrack.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.github.fluorumlabs.dtrack.model.PolicyViolation;
import java.util.UUID;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ViolationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ViolationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ViolationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getViolations
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @param showInactive Optionally includes inactive projects (optional)
     * @param violationState Filter by violation state (optional)
     * @param riskType Filter by risk type (optional)
     * @param policy Filter by policy (optional)
     * @param analysisState Filter by analysis state (optional)
     * @param occurredOnDateFrom Filter occurred on from (optional)
     * @param occurredOnDateTo Filter occurred on to (optional)
     * @param textSearchField Filter the text input in these fields (optional)
     * @param textSearchInput Filter by this text input (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for the entire portfolio </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViolationsCall(String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, Boolean showInactive, String violationState, String riskType, String policy, String analysisState, String occurredOnDateFrom, String occurredOnDateTo, String textSearchField, String textSearchInput, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/violation";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageNumber != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageNumber", pageNumber));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageSize", pageSize));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (sortName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sortName", sortName));
        }

        if (sortOrder != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sortOrder", sortOrder));
        }

        if (suppressed != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("suppressed", suppressed));
        }

        if (showInactive != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("showInactive", showInactive));
        }

        if (violationState != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("violationState", violationState));
        }

        if (riskType != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("riskType", riskType));
        }

        if (policy != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("policy", policy));
        }

        if (analysisState != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("analysisState", analysisState));
        }

        if (occurredOnDateFrom != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("occurredOnDateFrom", occurredOnDateFrom));
        }

        if (occurredOnDateTo != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("occurredOnDateTo", occurredOnDateTo));
        }

        if (textSearchField != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("textSearchField", textSearchField));
        }

        if (textSearchInput != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("textSearchInput", textSearchInput));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getViolationsValidateBeforeCall(String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, Boolean showInactive, String violationState, String riskType, String policy, String analysisState, String occurredOnDateFrom, String occurredOnDateTo, String textSearchField, String textSearchInput, final ApiCallback _callback) throws ApiException {
        return getViolationsCall(pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, showInactive, violationState, riskType, policy, analysisState, occurredOnDateFrom, occurredOnDateTo, textSearchField, textSearchInput, _callback);

    }

    /**
     * Returns a list of all policy violations for the entire portfolio
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_POLICY_VIOLATION&lt;/strong&gt;&lt;/p&gt;
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @param showInactive Optionally includes inactive projects (optional)
     * @param violationState Filter by violation state (optional)
     * @param riskType Filter by risk type (optional)
     * @param policy Filter by policy (optional)
     * @param analysisState Filter by analysis state (optional)
     * @param occurredOnDateFrom Filter occurred on from (optional)
     * @param occurredOnDateTo Filter occurred on to (optional)
     * @param textSearchField Filter the text input in these fields (optional)
     * @param textSearchInput Filter by this text input (optional)
     * @return List&lt;PolicyViolation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for the entire portfolio </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public List<PolicyViolation> getViolations(String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, Boolean showInactive, String violationState, String riskType, String policy, String analysisState, String occurredOnDateFrom, String occurredOnDateTo, String textSearchField, String textSearchInput) throws ApiException {
        ApiResponse<List<PolicyViolation>> localVarResp = getViolationsWithHttpInfo(pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, showInactive, violationState, riskType, policy, analysisState, occurredOnDateFrom, occurredOnDateTo, textSearchField, textSearchInput);
        return localVarResp.getData();
    }

    /**
     * Returns a list of all policy violations for the entire portfolio
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_POLICY_VIOLATION&lt;/strong&gt;&lt;/p&gt;
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @param showInactive Optionally includes inactive projects (optional)
     * @param violationState Filter by violation state (optional)
     * @param riskType Filter by risk type (optional)
     * @param policy Filter by policy (optional)
     * @param analysisState Filter by analysis state (optional)
     * @param occurredOnDateFrom Filter occurred on from (optional)
     * @param occurredOnDateTo Filter occurred on to (optional)
     * @param textSearchField Filter the text input in these fields (optional)
     * @param textSearchInput Filter by this text input (optional)
     * @return ApiResponse&lt;List&lt;PolicyViolation&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for the entire portfolio </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<PolicyViolation>> getViolationsWithHttpInfo(String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, Boolean showInactive, String violationState, String riskType, String policy, String analysisState, String occurredOnDateFrom, String occurredOnDateTo, String textSearchField, String textSearchInput) throws ApiException {
        okhttp3.Call localVarCall = getViolationsValidateBeforeCall(pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, showInactive, violationState, riskType, policy, analysisState, occurredOnDateFrom, occurredOnDateTo, textSearchField, textSearchInput, null);
        Type localVarReturnType = new TypeToken<List<PolicyViolation>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Returns a list of all policy violations for the entire portfolio (asynchronously)
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_POLICY_VIOLATION&lt;/strong&gt;&lt;/p&gt;
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @param showInactive Optionally includes inactive projects (optional)
     * @param violationState Filter by violation state (optional)
     * @param riskType Filter by risk type (optional)
     * @param policy Filter by policy (optional)
     * @param analysisState Filter by analysis state (optional)
     * @param occurredOnDateFrom Filter occurred on from (optional)
     * @param occurredOnDateTo Filter occurred on to (optional)
     * @param textSearchField Filter the text input in these fields (optional)
     * @param textSearchInput Filter by this text input (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for the entire portfolio </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViolationsAsync(String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, Boolean showInactive, String violationState, String riskType, String policy, String analysisState, String occurredOnDateFrom, String occurredOnDateTo, String textSearchField, String textSearchInput, final ApiCallback<List<PolicyViolation>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getViolationsValidateBeforeCall(pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, showInactive, violationState, riskType, policy, analysisState, occurredOnDateFrom, occurredOnDateTo, textSearchField, textSearchInput, _callback);
        Type localVarReturnType = new TypeToken<List<PolicyViolation>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getViolationsByComponent
     * @param uuid The UUID of the component (required)
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for a specific component </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access to the specified component is forbidden </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The component could not be found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViolationsByComponentCall(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/violation/component/{uuid}"
            .replace("{" + "uuid" + "}", localVarApiClient.escapeString(uuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageNumber != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageNumber", pageNumber));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageSize", pageSize));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (sortName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sortName", sortName));
        }

        if (sortOrder != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sortOrder", sortOrder));
        }

        if (suppressed != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("suppressed", suppressed));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getViolationsByComponentValidateBeforeCall(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'uuid' is set
        if (uuid == null) {
            throw new ApiException("Missing the required parameter 'uuid' when calling getViolationsByComponent(Async)");
        }

        return getViolationsByComponentCall(uuid, pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, _callback);

    }

    /**
     * Returns a list of all policy violations for a specific component
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_POLICY_VIOLATION&lt;/strong&gt;&lt;/p&gt;
     * @param uuid The UUID of the component (required)
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @return List&lt;PolicyViolation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for a specific component </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access to the specified component is forbidden </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The component could not be found </td><td>  -  </td></tr>
     </table>
     */
    public List<PolicyViolation> getViolationsByComponent(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed) throws ApiException {
        ApiResponse<List<PolicyViolation>> localVarResp = getViolationsByComponentWithHttpInfo(uuid, pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed);
        return localVarResp.getData();
    }

    /**
     * Returns a list of all policy violations for a specific component
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_POLICY_VIOLATION&lt;/strong&gt;&lt;/p&gt;
     * @param uuid The UUID of the component (required)
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @return ApiResponse&lt;List&lt;PolicyViolation&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for a specific component </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access to the specified component is forbidden </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The component could not be found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<PolicyViolation>> getViolationsByComponentWithHttpInfo(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed) throws ApiException {
        okhttp3.Call localVarCall = getViolationsByComponentValidateBeforeCall(uuid, pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, null);
        Type localVarReturnType = new TypeToken<List<PolicyViolation>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Returns a list of all policy violations for a specific component (asynchronously)
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_POLICY_VIOLATION&lt;/strong&gt;&lt;/p&gt;
     * @param uuid The UUID of the component (required)
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for a specific component </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access to the specified component is forbidden </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The component could not be found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViolationsByComponentAsync(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, final ApiCallback<List<PolicyViolation>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getViolationsByComponentValidateBeforeCall(uuid, pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, _callback);
        Type localVarReturnType = new TypeToken<List<PolicyViolation>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getViolationsByProject
     * @param uuid The UUID of the project (required)
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for a specific project </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access to the specified project is forbidden </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project could not be found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViolationsByProjectCall(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/violation/project/{uuid}"
            .replace("{" + "uuid" + "}", localVarApiClient.escapeString(uuid.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (pageNumber != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageNumber", pageNumber));
        }

        if (pageSize != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("pageSize", pageSize));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (sortName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sortName", sortName));
        }

        if (sortOrder != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sortOrder", sortOrder));
        }

        if (suppressed != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("suppressed", suppressed));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth", "BearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getViolationsByProjectValidateBeforeCall(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'uuid' is set
        if (uuid == null) {
            throw new ApiException("Missing the required parameter 'uuid' when calling getViolationsByProject(Async)");
        }

        return getViolationsByProjectCall(uuid, pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, _callback);

    }

    /**
     * Returns a list of all policy violations for a specific project
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_POLICY_VIOLATION&lt;/strong&gt;&lt;/p&gt;
     * @param uuid The UUID of the project (required)
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @return List&lt;PolicyViolation&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for a specific project </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access to the specified project is forbidden </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project could not be found </td><td>  -  </td></tr>
     </table>
     */
    public List<PolicyViolation> getViolationsByProject(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed) throws ApiException {
        ApiResponse<List<PolicyViolation>> localVarResp = getViolationsByProjectWithHttpInfo(uuid, pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed);
        return localVarResp.getData();
    }

    /**
     * Returns a list of all policy violations for a specific project
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_POLICY_VIOLATION&lt;/strong&gt;&lt;/p&gt;
     * @param uuid The UUID of the project (required)
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @return ApiResponse&lt;List&lt;PolicyViolation&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for a specific project </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access to the specified project is forbidden </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project could not be found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<PolicyViolation>> getViolationsByProjectWithHttpInfo(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed) throws ApiException {
        okhttp3.Call localVarCall = getViolationsByProjectValidateBeforeCall(uuid, pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, null);
        Type localVarReturnType = new TypeToken<List<PolicyViolation>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Returns a list of all policy violations for a specific project (asynchronously)
     * &lt;p&gt;Requires permission &lt;strong&gt;VIEW_POLICY_VIOLATION&lt;/strong&gt;&lt;/p&gt;
     * @param uuid The UUID of the project (required)
     * @param pageNumber The page to return. To be used in conjunction with &lt;code&gt;pageSize&lt;/code&gt;. (optional, default to 1)
     * @param pageSize Number of elements to return per page. To be used in conjunction with &lt;code&gt;pageNumber&lt;/code&gt;. (optional, default to 100)
     * @param offset Offset to start returning elements from. To be used in conjunction with &lt;code&gt;limit&lt;/code&gt;. (optional)
     * @param limit Number of elements to return per page. To be used in conjunction with &lt;code&gt;offset&lt;/code&gt;. (optional)
     * @param sortName Name of the resource field to sort on. (optional)
     * @param sortOrder Ordering of items when sorting with &lt;code&gt;sortName&lt;/code&gt;. (optional)
     * @param suppressed Optionally includes suppressed violations (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> A list of all policy violations for a specific project </td><td>  * X-Total-Count - The total number of vulnerabilities <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Access to the specified project is forbidden </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> The project could not be found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getViolationsByProjectAsync(UUID uuid, String pageNumber, String pageSize, String offset, String limit, String sortName, String sortOrder, Boolean suppressed, final ApiCallback<List<PolicyViolation>> _callback) throws ApiException {

        okhttp3.Call localVarCall = getViolationsByProjectValidateBeforeCall(uuid, pageNumber, pageSize, offset, limit, sortName, sortOrder, suppressed, _callback);
        Type localVarReturnType = new TypeToken<List<PolicyViolation>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
