/*
 * OWASP Dependency-Track
 * REST API of OWASP Dependency-Track
 *
 * The version of the OpenAPI document: 4.12.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.fluorumlabs.dtrack.JSON;

/**
 * AnalysisRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T15:50:33.163133100+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class AnalysisRequest {
  public static final String SERIALIZED_NAME_PROJECT = "project";
  @SerializedName(SERIALIZED_NAME_PROJECT)
  @javax.annotation.Nullable
  private String project;

  public static final String SERIALIZED_NAME_COMPONENT = "component";
  @SerializedName(SERIALIZED_NAME_COMPONENT)
  @javax.annotation.Nonnull
  private String component;

  public static final String SERIALIZED_NAME_VULNERABILITY = "vulnerability";
  @SerializedName(SERIALIZED_NAME_VULNERABILITY)
  @javax.annotation.Nonnull
  private String vulnerability;

  /**
   * Gets or Sets analysisState
   */
  @JsonAdapter(AnalysisStateEnum.Adapter.class)
  public enum AnalysisStateEnum {
    EXPLOITABLE("EXPLOITABLE"),
    
    IN_TRIAGE("IN_TRIAGE"),
    
    FALSE_POSITIVE("FALSE_POSITIVE"),
    
    NOT_AFFECTED("NOT_AFFECTED"),
    
    RESOLVED("RESOLVED"),
    
    NOT_SET("NOT_SET");

    private String value;

    AnalysisStateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AnalysisStateEnum fromValue(String value) {
      for (AnalysisStateEnum b : AnalysisStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AnalysisStateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AnalysisStateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AnalysisStateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AnalysisStateEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AnalysisStateEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ANALYSIS_STATE = "analysisState";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_STATE)
  @javax.annotation.Nullable
  private AnalysisStateEnum analysisState;

  /**
   * Gets or Sets analysisJustification
   */
  @JsonAdapter(AnalysisJustificationEnum.Adapter.class)
  public enum AnalysisJustificationEnum {
    CODE_NOT_PRESENT("CODE_NOT_PRESENT"),
    
    CODE_NOT_REACHABLE("CODE_NOT_REACHABLE"),
    
    REQUIRES_CONFIGURATION("REQUIRES_CONFIGURATION"),
    
    REQUIRES_DEPENDENCY("REQUIRES_DEPENDENCY"),
    
    REQUIRES_ENVIRONMENT("REQUIRES_ENVIRONMENT"),
    
    PROTECTED_BY_COMPILER("PROTECTED_BY_COMPILER"),
    
    PROTECTED_AT_RUNTIME("PROTECTED_AT_RUNTIME"),
    
    PROTECTED_AT_PERIMETER("PROTECTED_AT_PERIMETER"),
    
    PROTECTED_BY_MITIGATING_CONTROL("PROTECTED_BY_MITIGATING_CONTROL"),
    
    NOT_SET("NOT_SET");

    private String value;

    AnalysisJustificationEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AnalysisJustificationEnum fromValue(String value) {
      for (AnalysisJustificationEnum b : AnalysisJustificationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AnalysisJustificationEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AnalysisJustificationEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AnalysisJustificationEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AnalysisJustificationEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AnalysisJustificationEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ANALYSIS_JUSTIFICATION = "analysisJustification";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_JUSTIFICATION)
  @javax.annotation.Nullable
  private AnalysisJustificationEnum analysisJustification;

  /**
   * Gets or Sets analysisResponse
   */
  @JsonAdapter(AnalysisResponseEnum.Adapter.class)
  public enum AnalysisResponseEnum {
    CAN_NOT_FIX("CAN_NOT_FIX"),
    
    WILL_NOT_FIX("WILL_NOT_FIX"),
    
    UPDATE("UPDATE"),
    
    ROLLBACK("ROLLBACK"),
    
    WORKAROUND_AVAILABLE("WORKAROUND_AVAILABLE"),
    
    NOT_SET("NOT_SET");

    private String value;

    AnalysisResponseEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AnalysisResponseEnum fromValue(String value) {
      for (AnalysisResponseEnum b : AnalysisResponseEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AnalysisResponseEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AnalysisResponseEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AnalysisResponseEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AnalysisResponseEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AnalysisResponseEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ANALYSIS_RESPONSE = "analysisResponse";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_RESPONSE)
  @javax.annotation.Nullable
  private AnalysisResponseEnum analysisResponse;

  public static final String SERIALIZED_NAME_ANALYSIS_DETAILS = "analysisDetails";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_DETAILS)
  @javax.annotation.Nullable
  private String analysisDetails;

  public static final String SERIALIZED_NAME_COMMENT = "comment";
  @SerializedName(SERIALIZED_NAME_COMMENT)
  @javax.annotation.Nullable
  private String comment;

  public static final String SERIALIZED_NAME_IS_SUPPRESSED = "isSuppressed";
  @SerializedName(SERIALIZED_NAME_IS_SUPPRESSED)
  @javax.annotation.Nullable
  private Boolean isSuppressed;

  public static final String SERIALIZED_NAME_SUPPRESSED = "suppressed";
  @SerializedName(SERIALIZED_NAME_SUPPRESSED)
  @javax.annotation.Nullable
  private Boolean suppressed;

  public AnalysisRequest() {
  }

  public AnalysisRequest project(@javax.annotation.Nullable String project) {
    this.project = project;
    return this;
  }

  /**
   * Get project
   * @return project
   */
  @javax.annotation.Nullable
  public String getProject() {
    return project;
  }

  public void setProject(@javax.annotation.Nullable String project) {
    this.project = project;
  }


  public AnalysisRequest component(@javax.annotation.Nonnull String component) {
    this.component = component;
    return this;
  }

  /**
   * Get component
   * @return component
   */
  @javax.annotation.Nonnull
  public String getComponent() {
    return component;
  }

  public void setComponent(@javax.annotation.Nonnull String component) {
    this.component = component;
  }


  public AnalysisRequest vulnerability(@javax.annotation.Nonnull String vulnerability) {
    this.vulnerability = vulnerability;
    return this;
  }

  /**
   * Get vulnerability
   * @return vulnerability
   */
  @javax.annotation.Nonnull
  public String getVulnerability() {
    return vulnerability;
  }

  public void setVulnerability(@javax.annotation.Nonnull String vulnerability) {
    this.vulnerability = vulnerability;
  }


  public AnalysisRequest analysisState(@javax.annotation.Nullable AnalysisStateEnum analysisState) {
    this.analysisState = analysisState;
    return this;
  }

  /**
   * Get analysisState
   * @return analysisState
   */
  @javax.annotation.Nullable
  public AnalysisStateEnum getAnalysisState() {
    return analysisState;
  }

  public void setAnalysisState(@javax.annotation.Nullable AnalysisStateEnum analysisState) {
    this.analysisState = analysisState;
  }


  public AnalysisRequest analysisJustification(@javax.annotation.Nullable AnalysisJustificationEnum analysisJustification) {
    this.analysisJustification = analysisJustification;
    return this;
  }

  /**
   * Get analysisJustification
   * @return analysisJustification
   */
  @javax.annotation.Nullable
  public AnalysisJustificationEnum getAnalysisJustification() {
    return analysisJustification;
  }

  public void setAnalysisJustification(@javax.annotation.Nullable AnalysisJustificationEnum analysisJustification) {
    this.analysisJustification = analysisJustification;
  }


  public AnalysisRequest analysisResponse(@javax.annotation.Nullable AnalysisResponseEnum analysisResponse) {
    this.analysisResponse = analysisResponse;
    return this;
  }

  /**
   * Get analysisResponse
   * @return analysisResponse
   */
  @javax.annotation.Nullable
  public AnalysisResponseEnum getAnalysisResponse() {
    return analysisResponse;
  }

  public void setAnalysisResponse(@javax.annotation.Nullable AnalysisResponseEnum analysisResponse) {
    this.analysisResponse = analysisResponse;
  }


  public AnalysisRequest analysisDetails(@javax.annotation.Nullable String analysisDetails) {
    this.analysisDetails = analysisDetails;
    return this;
  }

  /**
   * Get analysisDetails
   * @return analysisDetails
   */
  @javax.annotation.Nullable
  public String getAnalysisDetails() {
    return analysisDetails;
  }

  public void setAnalysisDetails(@javax.annotation.Nullable String analysisDetails) {
    this.analysisDetails = analysisDetails;
  }


  public AnalysisRequest comment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Get comment
   * @return comment
   */
  @javax.annotation.Nullable
  public String getComment() {
    return comment;
  }

  public void setComment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
  }


  public AnalysisRequest isSuppressed(@javax.annotation.Nullable Boolean isSuppressed) {
    this.isSuppressed = isSuppressed;
    return this;
  }

  /**
   * Get isSuppressed
   * @return isSuppressed
   */
  @javax.annotation.Nullable
  public Boolean getIsSuppressed() {
    return isSuppressed;
  }

  public void setIsSuppressed(@javax.annotation.Nullable Boolean isSuppressed) {
    this.isSuppressed = isSuppressed;
  }


  public AnalysisRequest suppressed(@javax.annotation.Nullable Boolean suppressed) {
    this.suppressed = suppressed;
    return this;
  }

  /**
   * Get suppressed
   * @return suppressed
   */
  @javax.annotation.Nullable
  public Boolean getSuppressed() {
    return suppressed;
  }

  public void setSuppressed(@javax.annotation.Nullable Boolean suppressed) {
    this.suppressed = suppressed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalysisRequest analysisRequest = (AnalysisRequest) o;
    return Objects.equals(this.project, analysisRequest.project) &&
        Objects.equals(this.component, analysisRequest.component) &&
        Objects.equals(this.vulnerability, analysisRequest.vulnerability) &&
        Objects.equals(this.analysisState, analysisRequest.analysisState) &&
        Objects.equals(this.analysisJustification, analysisRequest.analysisJustification) &&
        Objects.equals(this.analysisResponse, analysisRequest.analysisResponse) &&
        Objects.equals(this.analysisDetails, analysisRequest.analysisDetails) &&
        Objects.equals(this.comment, analysisRequest.comment) &&
        Objects.equals(this.isSuppressed, analysisRequest.isSuppressed) &&
        Objects.equals(this.suppressed, analysisRequest.suppressed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(project, component, vulnerability, analysisState, analysisJustification, analysisResponse, analysisDetails, comment, isSuppressed, suppressed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalysisRequest {\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    vulnerability: ").append(toIndentedString(vulnerability)).append("\n");
    sb.append("    analysisState: ").append(toIndentedString(analysisState)).append("\n");
    sb.append("    analysisJustification: ").append(toIndentedString(analysisJustification)).append("\n");
    sb.append("    analysisResponse: ").append(toIndentedString(analysisResponse)).append("\n");
    sb.append("    analysisDetails: ").append(toIndentedString(analysisDetails)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    isSuppressed: ").append(toIndentedString(isSuppressed)).append("\n");
    sb.append("    suppressed: ").append(toIndentedString(suppressed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("project");
    openapiFields.add("component");
    openapiFields.add("vulnerability");
    openapiFields.add("analysisState");
    openapiFields.add("analysisJustification");
    openapiFields.add("analysisResponse");
    openapiFields.add("analysisDetails");
    openapiFields.add("comment");
    openapiFields.add("isSuppressed");
    openapiFields.add("suppressed");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("component");
    openapiRequiredFields.add("vulnerability");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AnalysisRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AnalysisRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AnalysisRequest is not found in the empty JSON string", AnalysisRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AnalysisRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AnalysisRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AnalysisRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("project") != null && !jsonObj.get("project").isJsonNull()) && !jsonObj.get("project").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `project` to be a primitive type in the JSON string but got `%s`", jsonObj.get("project").toString()));
      }
      if (!jsonObj.get("component").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `component` to be a primitive type in the JSON string but got `%s`", jsonObj.get("component").toString()));
      }
      if (!jsonObj.get("vulnerability").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vulnerability` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vulnerability").toString()));
      }
      if ((jsonObj.get("analysisState") != null && !jsonObj.get("analysisState").isJsonNull()) && !jsonObj.get("analysisState").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `analysisState` to be a primitive type in the JSON string but got `%s`", jsonObj.get("analysisState").toString()));
      }
      // validate the optional field `analysisState`
      if (jsonObj.get("analysisState") != null && !jsonObj.get("analysisState").isJsonNull()) {
        AnalysisStateEnum.validateJsonElement(jsonObj.get("analysisState"));
      }
      if ((jsonObj.get("analysisJustification") != null && !jsonObj.get("analysisJustification").isJsonNull()) && !jsonObj.get("analysisJustification").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `analysisJustification` to be a primitive type in the JSON string but got `%s`", jsonObj.get("analysisJustification").toString()));
      }
      // validate the optional field `analysisJustification`
      if (jsonObj.get("analysisJustification") != null && !jsonObj.get("analysisJustification").isJsonNull()) {
        AnalysisJustificationEnum.validateJsonElement(jsonObj.get("analysisJustification"));
      }
      if ((jsonObj.get("analysisResponse") != null && !jsonObj.get("analysisResponse").isJsonNull()) && !jsonObj.get("analysisResponse").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `analysisResponse` to be a primitive type in the JSON string but got `%s`", jsonObj.get("analysisResponse").toString()));
      }
      // validate the optional field `analysisResponse`
      if (jsonObj.get("analysisResponse") != null && !jsonObj.get("analysisResponse").isJsonNull()) {
        AnalysisResponseEnum.validateJsonElement(jsonObj.get("analysisResponse"));
      }
      if ((jsonObj.get("analysisDetails") != null && !jsonObj.get("analysisDetails").isJsonNull()) && !jsonObj.get("analysisDetails").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `analysisDetails` to be a primitive type in the JSON string but got `%s`", jsonObj.get("analysisDetails").toString()));
      }
      if ((jsonObj.get("comment") != null && !jsonObj.get("comment").isJsonNull()) && !jsonObj.get("comment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comment").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AnalysisRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AnalysisRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AnalysisRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AnalysisRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AnalysisRequest>() {
           @Override
           public void write(JsonWriter out, AnalysisRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AnalysisRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AnalysisRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AnalysisRequest
   * @throws IOException if the JSON string is invalid with respect to AnalysisRequest
   */
  public static AnalysisRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AnalysisRequest.class);
  }

  /**
   * Convert an instance of AnalysisRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

