/*
 * OWASP Dependency-Track
 * REST API of OWASP Dependency-Track
 *
 * The version of the OpenAPI document: 4.12.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import com.github.fluorumlabs.dtrack.model.NotificationPublisher;
import com.github.fluorumlabs.dtrack.model.Project;
import com.github.fluorumlabs.dtrack.model.Tag;
import com.github.fluorumlabs.dtrack.model.Team;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.fluorumlabs.dtrack.JSON;

/**
 * NotificationRule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T15:50:33.163133100+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class NotificationRule {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public static final String SERIALIZED_NAME_NOTIFY_CHILDREN = "notifyChildren";
  @SerializedName(SERIALIZED_NAME_NOTIFY_CHILDREN)
  @javax.annotation.Nullable
  private Boolean notifyChildren;

  public static final String SERIALIZED_NAME_LOG_SUCCESSFUL_PUBLISH = "logSuccessfulPublish";
  @SerializedName(SERIALIZED_NAME_LOG_SUCCESSFUL_PUBLISH)
  @javax.annotation.Nullable
  private Boolean logSuccessfulPublish;

  /**
   * Gets or Sets scope
   */
  @JsonAdapter(ScopeEnum.Adapter.class)
  public enum ScopeEnum {
    SYSTEM("SYSTEM"),
    
    PORTFOLIO("PORTFOLIO");

    private String value;

    ScopeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ScopeEnum fromValue(String value) {
      for (ScopeEnum b : ScopeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ScopeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ScopeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ScopeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ScopeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ScopeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SCOPE = "scope";
  @SerializedName(SERIALIZED_NAME_SCOPE)
  @javax.annotation.Nonnull
  private ScopeEnum scope;

  /**
   * Gets or Sets notificationLevel
   */
  @JsonAdapter(NotificationLevelEnum.Adapter.class)
  public enum NotificationLevelEnum {
    INFORMATIONAL("INFORMATIONAL"),
    
    WARNING("WARNING"),
    
    ERROR("ERROR");

    private String value;

    NotificationLevelEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static NotificationLevelEnum fromValue(String value) {
      for (NotificationLevelEnum b : NotificationLevelEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<NotificationLevelEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NotificationLevelEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public NotificationLevelEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return NotificationLevelEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      NotificationLevelEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_NOTIFICATION_LEVEL = "notificationLevel";
  @SerializedName(SERIALIZED_NAME_NOTIFICATION_LEVEL)
  @javax.annotation.Nullable
  private NotificationLevelEnum notificationLevel;

  public static final String SERIALIZED_NAME_PROJECTS = "projects";
  @SerializedName(SERIALIZED_NAME_PROJECTS)
  @javax.annotation.Nullable
  private List<Project> projects = new ArrayList<>();

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<Tag> tags = new ArrayList<>();

  public static final String SERIALIZED_NAME_TEAMS = "teams";
  @SerializedName(SERIALIZED_NAME_TEAMS)
  @javax.annotation.Nullable
  private List<Team> teams = new ArrayList<>();

  /**
   * Gets or Sets notifyOn
   */
  @JsonAdapter(NotifyOnEnum.Adapter.class)
  public enum NotifyOnEnum {
    CONFIGURATION("CONFIGURATION"),
    
    DATASOURCE_MIRRORING("DATASOURCE_MIRRORING"),
    
    REPOSITORY("REPOSITORY"),
    
    INTEGRATION("INTEGRATION"),
    
    INDEXING_SERVICE("INDEXING_SERVICE"),
    
    FILE_SYSTEM("FILE_SYSTEM"),
    
    ANALYZER("ANALYZER"),
    
    NEW_VULNERABILITY("NEW_VULNERABILITY"),
    
    NEW_VULNERABLE_DEPENDENCY("NEW_VULNERABLE_DEPENDENCY"),
    
    PROJECT_AUDIT_CHANGE("PROJECT_AUDIT_CHANGE"),
    
    BOM_CONSUMED("BOM_CONSUMED"),
    
    BOM_PROCESSED("BOM_PROCESSED"),
    
    BOM_PROCESSING_FAILED("BOM_PROCESSING_FAILED"),
    
    BOM_VALIDATION_FAILED("BOM_VALIDATION_FAILED"),
    
    VEX_CONSUMED("VEX_CONSUMED"),
    
    VEX_PROCESSED("VEX_PROCESSED"),
    
    POLICY_VIOLATION("POLICY_VIOLATION"),
    
    PROJECT_CREATED("PROJECT_CREATED"),
    
    USER_CREATED("USER_CREATED"),
    
    USER_DELETED("USER_DELETED");

    private String value;

    NotifyOnEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static NotifyOnEnum fromValue(String value) {
      for (NotifyOnEnum b : NotifyOnEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<NotifyOnEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NotifyOnEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public NotifyOnEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return NotifyOnEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      NotifyOnEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_NOTIFY_ON = "notifyOn";
  @SerializedName(SERIALIZED_NAME_NOTIFY_ON)
  @javax.annotation.Nullable
  private Set<NotifyOnEnum> notifyOn = new LinkedHashSet<>();

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  @javax.annotation.Nullable
  private String message;

  public static final String SERIALIZED_NAME_PUBLISHER = "publisher";
  @SerializedName(SERIALIZED_NAME_PUBLISHER)
  @javax.annotation.Nullable
  private NotificationPublisher publisher;

  public static final String SERIALIZED_NAME_PUBLISHER_CONFIG = "publisherConfig";
  @SerializedName(SERIALIZED_NAME_PUBLISHER_CONFIG)
  @javax.annotation.Nullable
  private String publisherConfig;

  public static final String SERIALIZED_NAME_UUID = "uuid";
  @SerializedName(SERIALIZED_NAME_UUID)
  @javax.annotation.Nonnull
  private UUID uuid;

  public NotificationRule() {
  }

  public NotificationRule name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public NotificationRule enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }


  public NotificationRule notifyChildren(@javax.annotation.Nullable Boolean notifyChildren) {
    this.notifyChildren = notifyChildren;
    return this;
  }

  /**
   * Get notifyChildren
   * @return notifyChildren
   */
  @javax.annotation.Nullable
  public Boolean getNotifyChildren() {
    return notifyChildren;
  }

  public void setNotifyChildren(@javax.annotation.Nullable Boolean notifyChildren) {
    this.notifyChildren = notifyChildren;
  }


  public NotificationRule logSuccessfulPublish(@javax.annotation.Nullable Boolean logSuccessfulPublish) {
    this.logSuccessfulPublish = logSuccessfulPublish;
    return this;
  }

  /**
   * Get logSuccessfulPublish
   * @return logSuccessfulPublish
   */
  @javax.annotation.Nullable
  public Boolean getLogSuccessfulPublish() {
    return logSuccessfulPublish;
  }

  public void setLogSuccessfulPublish(@javax.annotation.Nullable Boolean logSuccessfulPublish) {
    this.logSuccessfulPublish = logSuccessfulPublish;
  }


  public NotificationRule scope(@javax.annotation.Nonnull ScopeEnum scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope
   */
  @javax.annotation.Nonnull
  public ScopeEnum getScope() {
    return scope;
  }

  public void setScope(@javax.annotation.Nonnull ScopeEnum scope) {
    this.scope = scope;
  }


  public NotificationRule notificationLevel(@javax.annotation.Nullable NotificationLevelEnum notificationLevel) {
    this.notificationLevel = notificationLevel;
    return this;
  }

  /**
   * Get notificationLevel
   * @return notificationLevel
   */
  @javax.annotation.Nullable
  public NotificationLevelEnum getNotificationLevel() {
    return notificationLevel;
  }

  public void setNotificationLevel(@javax.annotation.Nullable NotificationLevelEnum notificationLevel) {
    this.notificationLevel = notificationLevel;
  }


  public NotificationRule projects(@javax.annotation.Nullable List<Project> projects) {
    this.projects = projects;
    return this;
  }

  public NotificationRule addProjectsItem(Project projectsItem) {
    if (this.projects == null) {
      this.projects = new ArrayList<>();
    }
    this.projects.add(projectsItem);
    return this;
  }

  /**
   * Get projects
   * @return projects
   */
  @javax.annotation.Nullable
  public List<Project> getProjects() {
    return projects;
  }

  public void setProjects(@javax.annotation.Nullable List<Project> projects) {
    this.projects = projects;
  }


  public NotificationRule tags(@javax.annotation.Nullable List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public NotificationRule addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<Tag> tags) {
    this.tags = tags;
  }


  public NotificationRule teams(@javax.annotation.Nullable List<Team> teams) {
    this.teams = teams;
    return this;
  }

  public NotificationRule addTeamsItem(Team teamsItem) {
    if (this.teams == null) {
      this.teams = new ArrayList<>();
    }
    this.teams.add(teamsItem);
    return this;
  }

  /**
   * Get teams
   * @return teams
   */
  @javax.annotation.Nullable
  public List<Team> getTeams() {
    return teams;
  }

  public void setTeams(@javax.annotation.Nullable List<Team> teams) {
    this.teams = teams;
  }


  public NotificationRule notifyOn(@javax.annotation.Nullable Set<NotifyOnEnum> notifyOn) {
    this.notifyOn = notifyOn;
    return this;
  }

  public NotificationRule addNotifyOnItem(NotifyOnEnum notifyOnItem) {
    if (this.notifyOn == null) {
      this.notifyOn = new LinkedHashSet<>();
    }
    this.notifyOn.add(notifyOnItem);
    return this;
  }

  /**
   * Get notifyOn
   * @return notifyOn
   */
  @javax.annotation.Nullable
  public Set<NotifyOnEnum> getNotifyOn() {
    return notifyOn;
  }

  public void setNotifyOn(@javax.annotation.Nullable Set<NotifyOnEnum> notifyOn) {
    this.notifyOn = notifyOn;
  }


  public NotificationRule message(@javax.annotation.Nullable String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }

  public void setMessage(@javax.annotation.Nullable String message) {
    this.message = message;
  }


  public NotificationRule publisher(@javax.annotation.Nullable NotificationPublisher publisher) {
    this.publisher = publisher;
    return this;
  }

  /**
   * Get publisher
   * @return publisher
   */
  @javax.annotation.Nullable
  public NotificationPublisher getPublisher() {
    return publisher;
  }

  public void setPublisher(@javax.annotation.Nullable NotificationPublisher publisher) {
    this.publisher = publisher;
  }


  public NotificationRule publisherConfig(@javax.annotation.Nullable String publisherConfig) {
    this.publisherConfig = publisherConfig;
    return this;
  }

  /**
   * Get publisherConfig
   * @return publisherConfig
   */
  @javax.annotation.Nullable
  public String getPublisherConfig() {
    return publisherConfig;
  }

  public void setPublisherConfig(@javax.annotation.Nullable String publisherConfig) {
    this.publisherConfig = publisherConfig;
  }


  public NotificationRule uuid(@javax.annotation.Nonnull UUID uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * Get uuid
   * @return uuid
   */
  @javax.annotation.Nonnull
  public UUID getUuid() {
    return uuid;
  }

  public void setUuid(@javax.annotation.Nonnull UUID uuid) {
    this.uuid = uuid;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationRule notificationRule = (NotificationRule) o;
    return Objects.equals(this.name, notificationRule.name) &&
        Objects.equals(this.enabled, notificationRule.enabled) &&
        Objects.equals(this.notifyChildren, notificationRule.notifyChildren) &&
        Objects.equals(this.logSuccessfulPublish, notificationRule.logSuccessfulPublish) &&
        Objects.equals(this.scope, notificationRule.scope) &&
        Objects.equals(this.notificationLevel, notificationRule.notificationLevel) &&
        Objects.equals(this.projects, notificationRule.projects) &&
        Objects.equals(this.tags, notificationRule.tags) &&
        Objects.equals(this.teams, notificationRule.teams) &&
        Objects.equals(this.notifyOn, notificationRule.notifyOn) &&
        Objects.equals(this.message, notificationRule.message) &&
        Objects.equals(this.publisher, notificationRule.publisher) &&
        Objects.equals(this.publisherConfig, notificationRule.publisherConfig) &&
        Objects.equals(this.uuid, notificationRule.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, enabled, notifyChildren, logSuccessfulPublish, scope, notificationLevel, projects, tags, teams, notifyOn, message, publisher, publisherConfig, uuid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationRule {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    notifyChildren: ").append(toIndentedString(notifyChildren)).append("\n");
    sb.append("    logSuccessfulPublish: ").append(toIndentedString(logSuccessfulPublish)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    notificationLevel: ").append(toIndentedString(notificationLevel)).append("\n");
    sb.append("    projects: ").append(toIndentedString(projects)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    teams: ").append(toIndentedString(teams)).append("\n");
    sb.append("    notifyOn: ").append(toIndentedString(notifyOn)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    publisher: ").append(toIndentedString(publisher)).append("\n");
    sb.append("    publisherConfig: ").append(toIndentedString(publisherConfig)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("enabled");
    openapiFields.add("notifyChildren");
    openapiFields.add("logSuccessfulPublish");
    openapiFields.add("scope");
    openapiFields.add("notificationLevel");
    openapiFields.add("projects");
    openapiFields.add("tags");
    openapiFields.add("teams");
    openapiFields.add("notifyOn");
    openapiFields.add("message");
    openapiFields.add("publisher");
    openapiFields.add("publisherConfig");
    openapiFields.add("uuid");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("scope");
    openapiRequiredFields.add("uuid");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NotificationRule
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NotificationRule.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in NotificationRule is not found in the empty JSON string", NotificationRule.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NotificationRule.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NotificationRule` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NotificationRule.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("scope").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `scope` to be a primitive type in the JSON string but got `%s`", jsonObj.get("scope").toString()));
      }
      // validate the required field `scope`
      ScopeEnum.validateJsonElement(jsonObj.get("scope"));
      if ((jsonObj.get("notificationLevel") != null && !jsonObj.get("notificationLevel").isJsonNull()) && !jsonObj.get("notificationLevel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `notificationLevel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notificationLevel").toString()));
      }
      // validate the optional field `notificationLevel`
      if (jsonObj.get("notificationLevel") != null && !jsonObj.get("notificationLevel").isJsonNull()) {
        NotificationLevelEnum.validateJsonElement(jsonObj.get("notificationLevel"));
      }
      if (jsonObj.get("projects") != null && !jsonObj.get("projects").isJsonNull()) {
        JsonArray jsonArrayprojects = jsonObj.getAsJsonArray("projects");
        if (jsonArrayprojects != null) {
          // ensure the json data is an array
          if (!jsonObj.get("projects").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `projects` to be an array in the JSON string but got `%s`", jsonObj.get("projects").toString()));
          }

          // validate the optional field `projects` (array)
          for (int i = 0; i < jsonArrayprojects.size(); i++) {
            Project.validateJsonElement(jsonArrayprojects.get(i));
          };
        }
      }
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull()) {
        JsonArray jsonArraytags = jsonObj.getAsJsonArray("tags");
        if (jsonArraytags != null) {
          // ensure the json data is an array
          if (!jsonObj.get("tags").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
          }

          // validate the optional field `tags` (array)
          for (int i = 0; i < jsonArraytags.size(); i++) {
            Tag.validateJsonElement(jsonArraytags.get(i));
          };
        }
      }
      if (jsonObj.get("teams") != null && !jsonObj.get("teams").isJsonNull()) {
        JsonArray jsonArrayteams = jsonObj.getAsJsonArray("teams");
        if (jsonArrayteams != null) {
          // ensure the json data is an array
          if (!jsonObj.get("teams").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `teams` to be an array in the JSON string but got `%s`", jsonObj.get("teams").toString()));
          }

          // validate the optional field `teams` (array)
          for (int i = 0; i < jsonArrayteams.size(); i++) {
            Team.validateJsonElement(jsonArrayteams.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("notifyOn") != null && !jsonObj.get("notifyOn").isJsonNull() && !jsonObj.get("notifyOn").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `notifyOn` to be an array in the JSON string but got `%s`", jsonObj.get("notifyOn").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      // validate the optional field `publisher`
      if (jsonObj.get("publisher") != null && !jsonObj.get("publisher").isJsonNull()) {
        NotificationPublisher.validateJsonElement(jsonObj.get("publisher"));
      }
      if ((jsonObj.get("publisherConfig") != null && !jsonObj.get("publisherConfig").isJsonNull()) && !jsonObj.get("publisherConfig").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `publisherConfig` to be a primitive type in the JSON string but got `%s`", jsonObj.get("publisherConfig").toString()));
      }
      if (!jsonObj.get("uuid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uuid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uuid").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NotificationRule.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NotificationRule' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NotificationRule> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NotificationRule.class));

       return (TypeAdapter<T>) new TypeAdapter<NotificationRule>() {
           @Override
           public void write(JsonWriter out, NotificationRule value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NotificationRule read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NotificationRule given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NotificationRule
   * @throws IOException if the JSON string is invalid with respect to NotificationRule
   */
  public static NotificationRule fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NotificationRule.class);
  }

  /**
   * Convert an instance of NotificationRule to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

