/*
 * OWASP Dependency-Track
 * REST API of OWASP Dependency-Track
 *
 * The version of the OpenAPI document: 4.12.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.fluorumlabs.dtrack.JSON;

/**
 * RepositoryMetaComponent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T15:50:33.163133100+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class RepositoryMetaComponent {
  /**
   * Gets or Sets repositoryType
   */
  @JsonAdapter(RepositoryTypeEnum.Adapter.class)
  public enum RepositoryTypeEnum {
    CPAN("CPAN"),
    
    MAVEN("MAVEN"),
    
    NPM("NPM"),
    
    GEM("GEM"),
    
    PYPI("PYPI"),
    
    NUGET("NUGET"),
    
    HEX("HEX"),
    
    COMPOSER("COMPOSER"),
    
    CARGO("CARGO"),
    
    GO_MODULES("GO_MODULES"),
    
    GITHUB("GITHUB"),
    
    HACKAGE("HACKAGE"),
    
    NIXPKGS("NIXPKGS"),
    
    UNSUPPORTED("UNSUPPORTED");

    private String value;

    RepositoryTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RepositoryTypeEnum fromValue(String value) {
      for (RepositoryTypeEnum b : RepositoryTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RepositoryTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RepositoryTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RepositoryTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RepositoryTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      RepositoryTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_REPOSITORY_TYPE = "repositoryType";
  @SerializedName(SERIALIZED_NAME_REPOSITORY_TYPE)
  @javax.annotation.Nonnull
  private RepositoryTypeEnum repositoryType;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  @javax.annotation.Nullable
  private String namespace;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_LATEST_VERSION = "latestVersion";
  @SerializedName(SERIALIZED_NAME_LATEST_VERSION)
  @javax.annotation.Nonnull
  private String latestVersion;

  public static final String SERIALIZED_NAME_PUBLISHED = "published";
  @SerializedName(SERIALIZED_NAME_PUBLISHED)
  @javax.annotation.Nonnull
  private Long published;

  public static final String SERIALIZED_NAME_LAST_CHECK = "lastCheck";
  @SerializedName(SERIALIZED_NAME_LAST_CHECK)
  @javax.annotation.Nonnull
  private Long lastCheck;

  public RepositoryMetaComponent() {
  }

  public RepositoryMetaComponent repositoryType(@javax.annotation.Nonnull RepositoryTypeEnum repositoryType) {
    this.repositoryType = repositoryType;
    return this;
  }

  /**
   * Get repositoryType
   * @return repositoryType
   */
  @javax.annotation.Nonnull
  public RepositoryTypeEnum getRepositoryType() {
    return repositoryType;
  }

  public void setRepositoryType(@javax.annotation.Nonnull RepositoryTypeEnum repositoryType) {
    this.repositoryType = repositoryType;
  }


  public RepositoryMetaComponent namespace(@javax.annotation.Nullable String namespace) {
    this.namespace = namespace;
    return this;
  }

  /**
   * Get namespace
   * @return namespace
   */
  @javax.annotation.Nullable
  public String getNamespace() {
    return namespace;
  }

  public void setNamespace(@javax.annotation.Nullable String namespace) {
    this.namespace = namespace;
  }


  public RepositoryMetaComponent name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public RepositoryMetaComponent latestVersion(@javax.annotation.Nonnull String latestVersion) {
    this.latestVersion = latestVersion;
    return this;
  }

  /**
   * Get latestVersion
   * @return latestVersion
   */
  @javax.annotation.Nonnull
  public String getLatestVersion() {
    return latestVersion;
  }

  public void setLatestVersion(@javax.annotation.Nonnull String latestVersion) {
    this.latestVersion = latestVersion;
  }


  public RepositoryMetaComponent published(@javax.annotation.Nonnull Long published) {
    this.published = published;
    return this;
  }

  /**
   * UNIX epoch timestamp in milliseconds
   * @return published
   */
  @javax.annotation.Nonnull
  public Long getPublished() {
    return published;
  }

  public void setPublished(@javax.annotation.Nonnull Long published) {
    this.published = published;
  }


  public RepositoryMetaComponent lastCheck(@javax.annotation.Nonnull Long lastCheck) {
    this.lastCheck = lastCheck;
    return this;
  }

  /**
   * UNIX epoch timestamp in milliseconds
   * @return lastCheck
   */
  @javax.annotation.Nonnull
  public Long getLastCheck() {
    return lastCheck;
  }

  public void setLastCheck(@javax.annotation.Nonnull Long lastCheck) {
    this.lastCheck = lastCheck;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryMetaComponent repositoryMetaComponent = (RepositoryMetaComponent) o;
    return Objects.equals(this.repositoryType, repositoryMetaComponent.repositoryType) &&
        Objects.equals(this.namespace, repositoryMetaComponent.namespace) &&
        Objects.equals(this.name, repositoryMetaComponent.name) &&
        Objects.equals(this.latestVersion, repositoryMetaComponent.latestVersion) &&
        Objects.equals(this.published, repositoryMetaComponent.published) &&
        Objects.equals(this.lastCheck, repositoryMetaComponent.lastCheck);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repositoryType, namespace, name, latestVersion, published, lastCheck);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryMetaComponent {\n");
    sb.append("    repositoryType: ").append(toIndentedString(repositoryType)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    latestVersion: ").append(toIndentedString(latestVersion)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    lastCheck: ").append(toIndentedString(lastCheck)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("repositoryType");
    openapiFields.add("namespace");
    openapiFields.add("name");
    openapiFields.add("latestVersion");
    openapiFields.add("published");
    openapiFields.add("lastCheck");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("repositoryType");
    openapiRequiredFields.add("name");
    openapiRequiredFields.add("latestVersion");
    openapiRequiredFields.add("published");
    openapiRequiredFields.add("lastCheck");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RepositoryMetaComponent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RepositoryMetaComponent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RepositoryMetaComponent is not found in the empty JSON string", RepositoryMetaComponent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RepositoryMetaComponent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RepositoryMetaComponent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RepositoryMetaComponent.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("repositoryType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `repositoryType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("repositoryType").toString()));
      }
      // validate the required field `repositoryType`
      RepositoryTypeEnum.validateJsonElement(jsonObj.get("repositoryType"));
      if ((jsonObj.get("namespace") != null && !jsonObj.get("namespace").isJsonNull()) && !jsonObj.get("namespace").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `namespace` to be a primitive type in the JSON string but got `%s`", jsonObj.get("namespace").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("latestVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `latestVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("latestVersion").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RepositoryMetaComponent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RepositoryMetaComponent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RepositoryMetaComponent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RepositoryMetaComponent.class));

       return (TypeAdapter<T>) new TypeAdapter<RepositoryMetaComponent>() {
           @Override
           public void write(JsonWriter out, RepositoryMetaComponent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RepositoryMetaComponent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RepositoryMetaComponent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RepositoryMetaComponent
   * @throws IOException if the JSON string is invalid with respect to RepositoryMetaComponent
   */
  public static RepositoryMetaComponent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RepositoryMetaComponent.class);
  }

  /**
   * Convert an instance of RepositoryMetaComponent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

