/*
 * OWASP Dependency-Track
 * REST API of OWASP Dependency-Track
 *
 * The version of the OpenAPI document: 4.12.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.fluorumlabs.dtrack.JSON;

/**
 * Score
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T15:50:33.163133100+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class Score {
  public static final String SERIALIZED_NAME_LIKELIHOOD_SCORE = "likelihoodScore";
  @SerializedName(SERIALIZED_NAME_LIKELIHOOD_SCORE)
  @javax.annotation.Nullable
  private Double likelihoodScore;

  public static final String SERIALIZED_NAME_TECHNICAL_IMPACT_SCORE = "technicalImpactScore";
  @SerializedName(SERIALIZED_NAME_TECHNICAL_IMPACT_SCORE)
  @javax.annotation.Nullable
  private Double technicalImpactScore;

  public static final String SERIALIZED_NAME_BUSINESS_IMPACT_SCORE = "businessImpactScore";
  @SerializedName(SERIALIZED_NAME_BUSINESS_IMPACT_SCORE)
  @javax.annotation.Nullable
  private Double businessImpactScore;

  /**
   * Gets or Sets likelihood
   */
  @JsonAdapter(LikelihoodEnum.Adapter.class)
  public enum LikelihoodEnum {
    HIGH("HIGH"),
    
    MEDIUM("MEDIUM"),
    
    LOW("LOW");

    private String value;

    LikelihoodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LikelihoodEnum fromValue(String value) {
      for (LikelihoodEnum b : LikelihoodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LikelihoodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LikelihoodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LikelihoodEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LikelihoodEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      LikelihoodEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_LIKELIHOOD = "likelihood";
  @SerializedName(SERIALIZED_NAME_LIKELIHOOD)
  @javax.annotation.Nullable
  private LikelihoodEnum likelihood;

  /**
   * Gets or Sets technicalImpact
   */
  @JsonAdapter(TechnicalImpactEnum.Adapter.class)
  public enum TechnicalImpactEnum {
    HIGH("HIGH"),
    
    MEDIUM("MEDIUM"),
    
    LOW("LOW");

    private String value;

    TechnicalImpactEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TechnicalImpactEnum fromValue(String value) {
      for (TechnicalImpactEnum b : TechnicalImpactEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TechnicalImpactEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TechnicalImpactEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TechnicalImpactEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TechnicalImpactEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TechnicalImpactEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TECHNICAL_IMPACT = "technicalImpact";
  @SerializedName(SERIALIZED_NAME_TECHNICAL_IMPACT)
  @javax.annotation.Nullable
  private TechnicalImpactEnum technicalImpact;

  /**
   * Gets or Sets businessImpact
   */
  @JsonAdapter(BusinessImpactEnum.Adapter.class)
  public enum BusinessImpactEnum {
    HIGH("HIGH"),
    
    MEDIUM("MEDIUM"),
    
    LOW("LOW");

    private String value;

    BusinessImpactEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BusinessImpactEnum fromValue(String value) {
      for (BusinessImpactEnum b : BusinessImpactEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<BusinessImpactEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BusinessImpactEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BusinessImpactEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return BusinessImpactEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      BusinessImpactEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_BUSINESS_IMPACT = "businessImpact";
  @SerializedName(SERIALIZED_NAME_BUSINESS_IMPACT)
  @javax.annotation.Nullable
  private BusinessImpactEnum businessImpact;

  public Score() {
  }

  public Score likelihoodScore(@javax.annotation.Nullable Double likelihoodScore) {
    this.likelihoodScore = likelihoodScore;
    return this;
  }

  /**
   * Get likelihoodScore
   * @return likelihoodScore
   */
  @javax.annotation.Nullable
  public Double getLikelihoodScore() {
    return likelihoodScore;
  }

  public void setLikelihoodScore(@javax.annotation.Nullable Double likelihoodScore) {
    this.likelihoodScore = likelihoodScore;
  }


  public Score technicalImpactScore(@javax.annotation.Nullable Double technicalImpactScore) {
    this.technicalImpactScore = technicalImpactScore;
    return this;
  }

  /**
   * Get technicalImpactScore
   * @return technicalImpactScore
   */
  @javax.annotation.Nullable
  public Double getTechnicalImpactScore() {
    return technicalImpactScore;
  }

  public void setTechnicalImpactScore(@javax.annotation.Nullable Double technicalImpactScore) {
    this.technicalImpactScore = technicalImpactScore;
  }


  public Score businessImpactScore(@javax.annotation.Nullable Double businessImpactScore) {
    this.businessImpactScore = businessImpactScore;
    return this;
  }

  /**
   * Get businessImpactScore
   * @return businessImpactScore
   */
  @javax.annotation.Nullable
  public Double getBusinessImpactScore() {
    return businessImpactScore;
  }

  public void setBusinessImpactScore(@javax.annotation.Nullable Double businessImpactScore) {
    this.businessImpactScore = businessImpactScore;
  }


  public Score likelihood(@javax.annotation.Nullable LikelihoodEnum likelihood) {
    this.likelihood = likelihood;
    return this;
  }

  /**
   * Get likelihood
   * @return likelihood
   */
  @javax.annotation.Nullable
  public LikelihoodEnum getLikelihood() {
    return likelihood;
  }

  public void setLikelihood(@javax.annotation.Nullable LikelihoodEnum likelihood) {
    this.likelihood = likelihood;
  }


  public Score technicalImpact(@javax.annotation.Nullable TechnicalImpactEnum technicalImpact) {
    this.technicalImpact = technicalImpact;
    return this;
  }

  /**
   * Get technicalImpact
   * @return technicalImpact
   */
  @javax.annotation.Nullable
  public TechnicalImpactEnum getTechnicalImpact() {
    return technicalImpact;
  }

  public void setTechnicalImpact(@javax.annotation.Nullable TechnicalImpactEnum technicalImpact) {
    this.technicalImpact = technicalImpact;
  }


  public Score businessImpact(@javax.annotation.Nullable BusinessImpactEnum businessImpact) {
    this.businessImpact = businessImpact;
    return this;
  }

  /**
   * Get businessImpact
   * @return businessImpact
   */
  @javax.annotation.Nullable
  public BusinessImpactEnum getBusinessImpact() {
    return businessImpact;
  }

  public void setBusinessImpact(@javax.annotation.Nullable BusinessImpactEnum businessImpact) {
    this.businessImpact = businessImpact;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Score score = (Score) o;
    return Objects.equals(this.likelihoodScore, score.likelihoodScore) &&
        Objects.equals(this.technicalImpactScore, score.technicalImpactScore) &&
        Objects.equals(this.businessImpactScore, score.businessImpactScore) &&
        Objects.equals(this.likelihood, score.likelihood) &&
        Objects.equals(this.technicalImpact, score.technicalImpact) &&
        Objects.equals(this.businessImpact, score.businessImpact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(likelihoodScore, technicalImpactScore, businessImpactScore, likelihood, technicalImpact, businessImpact);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Score {\n");
    sb.append("    likelihoodScore: ").append(toIndentedString(likelihoodScore)).append("\n");
    sb.append("    technicalImpactScore: ").append(toIndentedString(technicalImpactScore)).append("\n");
    sb.append("    businessImpactScore: ").append(toIndentedString(businessImpactScore)).append("\n");
    sb.append("    likelihood: ").append(toIndentedString(likelihood)).append("\n");
    sb.append("    technicalImpact: ").append(toIndentedString(technicalImpact)).append("\n");
    sb.append("    businessImpact: ").append(toIndentedString(businessImpact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("likelihoodScore");
    openapiFields.add("technicalImpactScore");
    openapiFields.add("businessImpactScore");
    openapiFields.add("likelihood");
    openapiFields.add("technicalImpact");
    openapiFields.add("businessImpact");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Score
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Score.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Score is not found in the empty JSON string", Score.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Score.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Score` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("likelihood") != null && !jsonObj.get("likelihood").isJsonNull()) && !jsonObj.get("likelihood").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `likelihood` to be a primitive type in the JSON string but got `%s`", jsonObj.get("likelihood").toString()));
      }
      // validate the optional field `likelihood`
      if (jsonObj.get("likelihood") != null && !jsonObj.get("likelihood").isJsonNull()) {
        LikelihoodEnum.validateJsonElement(jsonObj.get("likelihood"));
      }
      if ((jsonObj.get("technicalImpact") != null && !jsonObj.get("technicalImpact").isJsonNull()) && !jsonObj.get("technicalImpact").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `technicalImpact` to be a primitive type in the JSON string but got `%s`", jsonObj.get("technicalImpact").toString()));
      }
      // validate the optional field `technicalImpact`
      if (jsonObj.get("technicalImpact") != null && !jsonObj.get("technicalImpact").isJsonNull()) {
        TechnicalImpactEnum.validateJsonElement(jsonObj.get("technicalImpact"));
      }
      if ((jsonObj.get("businessImpact") != null && !jsonObj.get("businessImpact").isJsonNull()) && !jsonObj.get("businessImpact").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `businessImpact` to be a primitive type in the JSON string but got `%s`", jsonObj.get("businessImpact").toString()));
      }
      // validate the optional field `businessImpact`
      if (jsonObj.get("businessImpact") != null && !jsonObj.get("businessImpact").isJsonNull()) {
        BusinessImpactEnum.validateJsonElement(jsonObj.get("businessImpact"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Score.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Score' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Score> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Score.class));

       return (TypeAdapter<T>) new TypeAdapter<Score>() {
           @Override
           public void write(JsonWriter out, Score value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Score read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Score given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Score
   * @throws IOException if the JSON string is invalid with respect to Score
   */
  public static Score fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Score.class);
  }

  /**
   * Convert an instance of Score to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

