/*
 * OWASP Dependency-Track
 * REST API of OWASP Dependency-Track
 *
 * The version of the OpenAPI document: 4.12.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import com.github.fluorumlabs.dtrack.model.ViolationAnalysisComment;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.github.fluorumlabs.dtrack.JSON;

/**
 * ViolationAnalysis
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-04T15:50:33.163133100+01:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class ViolationAnalysis {
  /**
   * Gets or Sets analysisState
   */
  @JsonAdapter(AnalysisStateEnum.Adapter.class)
  public enum AnalysisStateEnum {
    APPROVED("APPROVED"),
    
    REJECTED("REJECTED"),
    
    NOT_SET("NOT_SET");

    private String value;

    AnalysisStateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AnalysisStateEnum fromValue(String value) {
      for (AnalysisStateEnum b : AnalysisStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AnalysisStateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AnalysisStateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AnalysisStateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AnalysisStateEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AnalysisStateEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ANALYSIS_STATE = "analysisState";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_STATE)
  @javax.annotation.Nonnull
  private AnalysisStateEnum analysisState;

  public static final String SERIALIZED_NAME_ANALYSIS_COMMENTS = "analysisComments";
  @SerializedName(SERIALIZED_NAME_ANALYSIS_COMMENTS)
  @javax.annotation.Nullable
  private List<ViolationAnalysisComment> analysisComments = new ArrayList<>();

  /**
   * Gets or Sets violationAnalysisState
   */
  @JsonAdapter(ViolationAnalysisStateEnum.Adapter.class)
  public enum ViolationAnalysisStateEnum {
    APPROVED("APPROVED"),
    
    REJECTED("REJECTED"),
    
    NOT_SET("NOT_SET");

    private String value;

    ViolationAnalysisStateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ViolationAnalysisStateEnum fromValue(String value) {
      for (ViolationAnalysisStateEnum b : ViolationAnalysisStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ViolationAnalysisStateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ViolationAnalysisStateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ViolationAnalysisStateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ViolationAnalysisStateEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ViolationAnalysisStateEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_VIOLATION_ANALYSIS_STATE = "violationAnalysisState";
  @SerializedName(SERIALIZED_NAME_VIOLATION_ANALYSIS_STATE)
  @javax.annotation.Nullable
  private ViolationAnalysisStateEnum violationAnalysisState;

  public static final String SERIALIZED_NAME_IS_SUPPRESSED = "isSuppressed";
  @SerializedName(SERIALIZED_NAME_IS_SUPPRESSED)
  @javax.annotation.Nullable
  private Boolean isSuppressed;

  public ViolationAnalysis() {
  }

  public ViolationAnalysis analysisState(@javax.annotation.Nonnull AnalysisStateEnum analysisState) {
    this.analysisState = analysisState;
    return this;
  }

  /**
   * Get analysisState
   * @return analysisState
   */
  @javax.annotation.Nonnull
  public AnalysisStateEnum getAnalysisState() {
    return analysisState;
  }

  public void setAnalysisState(@javax.annotation.Nonnull AnalysisStateEnum analysisState) {
    this.analysisState = analysisState;
  }


  public ViolationAnalysis analysisComments(@javax.annotation.Nullable List<ViolationAnalysisComment> analysisComments) {
    this.analysisComments = analysisComments;
    return this;
  }

  public ViolationAnalysis addAnalysisCommentsItem(ViolationAnalysisComment analysisCommentsItem) {
    if (this.analysisComments == null) {
      this.analysisComments = new ArrayList<>();
    }
    this.analysisComments.add(analysisCommentsItem);
    return this;
  }

  /**
   * Get analysisComments
   * @return analysisComments
   */
  @javax.annotation.Nullable
  public List<ViolationAnalysisComment> getAnalysisComments() {
    return analysisComments;
  }

  public void setAnalysisComments(@javax.annotation.Nullable List<ViolationAnalysisComment> analysisComments) {
    this.analysisComments = analysisComments;
  }


  public ViolationAnalysis violationAnalysisState(@javax.annotation.Nullable ViolationAnalysisStateEnum violationAnalysisState) {
    this.violationAnalysisState = violationAnalysisState;
    return this;
  }

  /**
   * Get violationAnalysisState
   * @return violationAnalysisState
   */
  @javax.annotation.Nullable
  public ViolationAnalysisStateEnum getViolationAnalysisState() {
    return violationAnalysisState;
  }

  public void setViolationAnalysisState(@javax.annotation.Nullable ViolationAnalysisStateEnum violationAnalysisState) {
    this.violationAnalysisState = violationAnalysisState;
  }


  public ViolationAnalysis isSuppressed(@javax.annotation.Nullable Boolean isSuppressed) {
    this.isSuppressed = isSuppressed;
    return this;
  }

  /**
   * Get isSuppressed
   * @return isSuppressed
   */
  @javax.annotation.Nullable
  public Boolean getIsSuppressed() {
    return isSuppressed;
  }

  public void setIsSuppressed(@javax.annotation.Nullable Boolean isSuppressed) {
    this.isSuppressed = isSuppressed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ViolationAnalysis violationAnalysis = (ViolationAnalysis) o;
    return Objects.equals(this.analysisState, violationAnalysis.analysisState) &&
        Objects.equals(this.analysisComments, violationAnalysis.analysisComments) &&
        Objects.equals(this.violationAnalysisState, violationAnalysis.violationAnalysisState) &&
        Objects.equals(this.isSuppressed, violationAnalysis.isSuppressed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analysisState, analysisComments, violationAnalysisState, isSuppressed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ViolationAnalysis {\n");
    sb.append("    analysisState: ").append(toIndentedString(analysisState)).append("\n");
    sb.append("    analysisComments: ").append(toIndentedString(analysisComments)).append("\n");
    sb.append("    violationAnalysisState: ").append(toIndentedString(violationAnalysisState)).append("\n");
    sb.append("    isSuppressed: ").append(toIndentedString(isSuppressed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("analysisState");
    openapiFields.add("analysisComments");
    openapiFields.add("violationAnalysisState");
    openapiFields.add("isSuppressed");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("analysisState");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ViolationAnalysis
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ViolationAnalysis.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ViolationAnalysis is not found in the empty JSON string", ViolationAnalysis.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ViolationAnalysis.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ViolationAnalysis` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ViolationAnalysis.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("analysisState").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `analysisState` to be a primitive type in the JSON string but got `%s`", jsonObj.get("analysisState").toString()));
      }
      // validate the required field `analysisState`
      AnalysisStateEnum.validateJsonElement(jsonObj.get("analysisState"));
      if (jsonObj.get("analysisComments") != null && !jsonObj.get("analysisComments").isJsonNull()) {
        JsonArray jsonArrayanalysisComments = jsonObj.getAsJsonArray("analysisComments");
        if (jsonArrayanalysisComments != null) {
          // ensure the json data is an array
          if (!jsonObj.get("analysisComments").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `analysisComments` to be an array in the JSON string but got `%s`", jsonObj.get("analysisComments").toString()));
          }

          // validate the optional field `analysisComments` (array)
          for (int i = 0; i < jsonArrayanalysisComments.size(); i++) {
            ViolationAnalysisComment.validateJsonElement(jsonArrayanalysisComments.get(i));
          };
        }
      }
      if ((jsonObj.get("violationAnalysisState") != null && !jsonObj.get("violationAnalysisState").isJsonNull()) && !jsonObj.get("violationAnalysisState").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `violationAnalysisState` to be a primitive type in the JSON string but got `%s`", jsonObj.get("violationAnalysisState").toString()));
      }
      // validate the optional field `violationAnalysisState`
      if (jsonObj.get("violationAnalysisState") != null && !jsonObj.get("violationAnalysisState").isJsonNull()) {
        ViolationAnalysisStateEnum.validateJsonElement(jsonObj.get("violationAnalysisState"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ViolationAnalysis.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ViolationAnalysis' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ViolationAnalysis> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ViolationAnalysis.class));

       return (TypeAdapter<T>) new TypeAdapter<ViolationAnalysis>() {
           @Override
           public void write(JsonWriter out, ViolationAnalysis value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ViolationAnalysis read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ViolationAnalysis given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ViolationAnalysis
   * @throws IOException if the JSON string is invalid with respect to ViolationAnalysis
   */
  public static ViolationAnalysis fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ViolationAnalysis.class);
  }

  /**
   * Convert an instance of ViolationAnalysis to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

