/*
 * OWASP Dependency-Track
 * REST API of OWASP Dependency-Track
 *
 * OpenAPI spec version: 4.12.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.fluorumlabs.dtrack.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ViolationAnalysisRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-11T11:08:28.654737800+01:00[Europe/Berlin]")

public class ViolationAnalysisRequest {
  @SerializedName("component")
  private String component = null;

  @SerializedName("policyViolation")
  private String policyViolation = null;

  /**
   * Gets or Sets analysisState
   */
  @JsonAdapter(AnalysisStateEnum.Adapter.class)
  public enum AnalysisStateEnum {
    @SerializedName("APPROVED")
    APPROVED("APPROVED"),
    @SerializedName("REJECTED")
    REJECTED("REJECTED"),
    @SerializedName("NOT_SET")
    NOT_SET("NOT_SET");

    private String value;

    AnalysisStateEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AnalysisStateEnum fromValue(String input) {
      for (AnalysisStateEnum b : AnalysisStateEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AnalysisStateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AnalysisStateEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public AnalysisStateEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return AnalysisStateEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("analysisState")
  private AnalysisStateEnum analysisState = null;

  @SerializedName("comment")
  private String comment = null;

  @SerializedName("isSuppressed")
  private Boolean isSuppressed = null;

  @SerializedName("suppressed")
  private Boolean suppressed = null;

  public ViolationAnalysisRequest component(String component) {
    this.component = component;
    return this;
  }

   /**
   * Get component
   * @return component
  **/
  @Schema(required = true, description = "")
  public String getComponent() {
    return component;
  }

  public void setComponent(String component) {
    this.component = component;
  }

  public ViolationAnalysisRequest policyViolation(String policyViolation) {
    this.policyViolation = policyViolation;
    return this;
  }

   /**
   * Get policyViolation
   * @return policyViolation
  **/
  @Schema(required = true, description = "")
  public String getPolicyViolation() {
    return policyViolation;
  }

  public void setPolicyViolation(String policyViolation) {
    this.policyViolation = policyViolation;
  }

  public ViolationAnalysisRequest analysisState(AnalysisStateEnum analysisState) {
    this.analysisState = analysisState;
    return this;
  }

   /**
   * Get analysisState
   * @return analysisState
  **/
  @Schema(description = "")
  public AnalysisStateEnum getAnalysisState() {
    return analysisState;
  }

  public void setAnalysisState(AnalysisStateEnum analysisState) {
    this.analysisState = analysisState;
  }

  public ViolationAnalysisRequest comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @Schema(description = "")
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public ViolationAnalysisRequest isSuppressed(Boolean isSuppressed) {
    this.isSuppressed = isSuppressed;
    return this;
  }

   /**
   * Get isSuppressed
   * @return isSuppressed
  **/
  @Schema(description = "")
  public Boolean isIsSuppressed() {
    return isSuppressed;
  }

  public void setIsSuppressed(Boolean isSuppressed) {
    this.isSuppressed = isSuppressed;
  }

  public ViolationAnalysisRequest suppressed(Boolean suppressed) {
    this.suppressed = suppressed;
    return this;
  }

   /**
   * Get suppressed
   * @return suppressed
  **/
  @Schema(description = "")
  public Boolean isSuppressed() {
    return suppressed;
  }

  public void setSuppressed(Boolean suppressed) {
    this.suppressed = suppressed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ViolationAnalysisRequest violationAnalysisRequest = (ViolationAnalysisRequest) o;
    return Objects.equals(this.component, violationAnalysisRequest.component) &&
        Objects.equals(this.policyViolation, violationAnalysisRequest.policyViolation) &&
        Objects.equals(this.analysisState, violationAnalysisRequest.analysisState) &&
        Objects.equals(this.comment, violationAnalysisRequest.comment) &&
        Objects.equals(this.isSuppressed, violationAnalysisRequest.isSuppressed) &&
        Objects.equals(this.suppressed, violationAnalysisRequest.suppressed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(component, policyViolation, analysisState, comment, isSuppressed, suppressed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ViolationAnalysisRequest {\n");
    
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    policyViolation: ").append(toIndentedString(policyViolation)).append("\n");
    sb.append("    analysisState: ").append(toIndentedString(analysisState)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    isSuppressed: ").append(toIndentedString(isSuppressed)).append("\n");
    sb.append("    suppressed: ").append(toIndentedString(suppressed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
