/*
 * OWASP Dependency-Track
 * REST API of OWASP Dependency-Track
 *
 * OpenAPI spec version: 4.12.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vaadin.dtrack.api;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * TagListResponseItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-12T17:49:40.645296700+01:00[Europe/Berlin]")

public class TagListResponseItem {
  @SerializedName("name")
  private String name = null;

  @SerializedName("projectCount")
  private Long projectCount = null;

  @SerializedName("policyCount")
  private Long policyCount = null;

  @SerializedName("notificationRuleCount")
  private Long notificationRuleCount = null;

  public TagListResponseItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TagListResponseItem projectCount(Long projectCount) {
    this.projectCount = projectCount;
    return this;
  }

   /**
   * Get projectCount
   * @return projectCount
  **/
  @Schema(description = "")
  public Long getProjectCount() {
    return projectCount;
  }

  public void setProjectCount(Long projectCount) {
    this.projectCount = projectCount;
  }

  public TagListResponseItem policyCount(Long policyCount) {
    this.policyCount = policyCount;
    return this;
  }

   /**
   * Get policyCount
   * @return policyCount
  **/
  @Schema(description = "")
  public Long getPolicyCount() {
    return policyCount;
  }

  public void setPolicyCount(Long policyCount) {
    this.policyCount = policyCount;
  }

  public TagListResponseItem notificationRuleCount(Long notificationRuleCount) {
    this.notificationRuleCount = notificationRuleCount;
    return this;
  }

   /**
   * Get notificationRuleCount
   * @return notificationRuleCount
  **/
  @Schema(description = "")
  public Long getNotificationRuleCount() {
    return notificationRuleCount;
  }

  public void setNotificationRuleCount(Long notificationRuleCount) {
    this.notificationRuleCount = notificationRuleCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagListResponseItem tagListResponseItem = (TagListResponseItem) o;
    return Objects.equals(this.name, tagListResponseItem.name) &&
        Objects.equals(this.projectCount, tagListResponseItem.projectCount) &&
        Objects.equals(this.policyCount, tagListResponseItem.policyCount) &&
        Objects.equals(this.notificationRuleCount, tagListResponseItem.notificationRuleCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, projectCount, policyCount, notificationRuleCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagListResponseItem {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    projectCount: ").append(toIndentedString(projectCount)).append("\n");
    sb.append("    policyCount: ").append(toIndentedString(policyCount)).append("\n");
    sb.append("    notificationRuleCount: ").append(toIndentedString(notificationRuleCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
